{
    "openapi": "3.0.n",
    "info": {
        "title": "Rental Cars API",
        "description": "This is the documentation for the Rental Cars API. It's a test documentation, whose focus is to use the swagger-ui library as a way to learn more about documentation and get to know more about this amazing library.",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "1.0.0"
    },
    "paths": {
        "/sessions": {
            "post": {
                "tags": [
                    "Session"
                ],
                "summary": "Authentication user",
                "description": "Authenticate a user",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "email": "Enter already registered email",
                                "password": "Enter already registered password"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "500": {
                        "description": "Email or passwaord incorrect!"
                    }
                }
            }
        },
        "/categories": {
            "post": {
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "description": "Route for creating a new vehicle category.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/schemaCategoriesSpecifications"
                            },
                            "example": {
                                "name": "Create a new example for category name",
                                "description": "Create a new example for category description"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Category already exist"
                    }
                }
            },
            "get": {
                "tags": [
                    "Category"
                ],
                "summary": "List all categories",
                "description": "List all already created categories.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/specifications": {
            "post": {
                "tags": [
                    "Specifications"
                ],
                "summary": "Create a new specification",
                "description": "Route for creating a new vehicle specification.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/schemaCategoriesSpecifications"
                            },
                            "example": {
                                "name": "Create a new example for specification name",
                                "description": "Create a new example for specification description"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Specification already exist"
                    }
                }
            },
            "get": {
                "tags": [
                    "Specifications"
                ],
                "summary": "List all specifications",
                "description": "List all already created specifications.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user",
                "description": "Route for creating a new user.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "username": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "driver_license": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "name": "Create a new example for name of user",
                                    "username": "Create a new example for username of user",
                                    "password": "Create a new example for password of user",
                                    "email": "Create a new example for email of user",
                                    "driver_license": "Create a new example for driver license of user"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Username or e-mail already exist"
                    }
                }
            }
        },
        "/cars": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "summary": "Create a new car",
                "description": "Route for creating a new car.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/definitions/Car"
                            },
                            "example": {
                                "name": "Create a new example for name of car",
                                "description": "Create a new example for car description",
                                "daily_rate": "Create a new example for the daily value of the car",
                                "license_plate": "Create a new example for license plate of the car",
                                "fine_amount": "Create a new example for the amount of the fine in the car",
                                "brand": "Create a new example for brand of car",
                                "category_id": "Enter the id of an already created category"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "daily_rate": {
                                            "type": "number"
                                        },
                                        "license_plate": {
                                            "type": "string"
                                        },
                                        "fine_amount": {
                                            "type": "number"
                                        },
                                        "brand": {
                                            "type": "string"
                                        },
                                        "category_id": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Car license plate already exist"
                    }
                }
            },
            "get": {
                "tags": [
                    "Cars"
                ],
                "summary": "List all cars",
                "description": "Lists all registered cars (available or unavailable).",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "avaliable": {
                                                "type": "boolean"
                                            },
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            },
                                            "daily_rate": {
                                                "type": "number"
                                            },
                                            "license_plate": {
                                                "type": "string"
                                            },
                                            "fine_amount": {
                                                "type": "number"
                                            },
                                            "brand": {
                                                "type": "string"
                                            },
                                            "category_id": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "id": "ID of car",
                                    "avaliable": "true or false",
                                    "name": "Name of car",
                                    "description": "Description of car",
                                    "daily_rate": "Value of daily rate of car",
                                    "license_plate": "License plate of car",
                                    "fine_amount": "Value of fine amount of car",
                                    "brand": "Brand of car",
                                    "category_id": "Category id of car",
                                    "created_at": "Timestamp of registered car"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/cars/available": {
            "get": {
                "tags": [
                    "Cars"
                ],
                "summary": "List avaliable cars",
                "description": "List all cars with 'avaliable' status for rent.",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "query",
                        "name": "name",
                        "requerid": false,
                        "description": "name of car",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "query",
                        "name": "brand",
                        "requerid": false,
                        "description": "brand of car",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "in": "query",
                        "name": "category_id",
                        "requerid": false,
                        "description": "category id of car",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "avaliable": {
                                                "type": "boolean"
                                            },
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            },
                                            "daily_rate": {
                                                "type": "number"
                                            },
                                            "license_plate": {
                                                "type": "string"
                                            },
                                            "fine_amount": {
                                                "type": "number"
                                            },
                                            "brand": {
                                                "type": "string"
                                            },
                                            "category_id": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "id": "ID of car",
                                    "avaliable": "true or false",
                                    "name": "Name of car",
                                    "description": "Description of car",
                                    "daily_rate": "Value of daily rate of car",
                                    "license_plate": "License plate of car",
                                    "fine_amount": "Value of fine amount of car",
                                    "brand": "Brand of car",
                                    "category_id": "Category id of car",
                                    "created_at": "Timestamp of registered car"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error. Invalid input syntax"
                    }
                }
            }
        },
        "/cars/specifications/{car_id}": {
            "post": {
                "tags": [
                    "Cars"
                ],
                "summary": "Create a new car-especification.",
                "description": "Creates a new car specification in the 'specifications_cars' table",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "car_id",
                        "requerid": true,
                        "description": "ID of car",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "specifications_id": {
                                        "type": "string"
                                    }
                                }
                            },
                            "example": {
                                "specifications_id": [
                                    "Enter already registered specification id"
                                ]
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "avaliable": {
                                            "type": "boolean"
                                        },
                                        "name": {
                                            "type": "string"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "daily_rate": {
                                            "type": "number"
                                        },
                                        "license_plate": {
                                            "type": "string"
                                        },
                                        "fine_amount": {
                                            "type": "number"
                                        },
                                        "brand": {
                                            "type": "string"
                                        },
                                        "category_id": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "specifications": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "description": {
                                                        "type": "string"
                                                    },
                                                    "created_at": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "example": {
                                    "id": "ID of car",
                                    "avaliable": "true or false",
                                    "name": "Name of car",
                                    "description": "Description of car",
                                    "daily_rate": "Value of daily rate of car",
                                    "license_plate": "License plate of car",
                                    "fine_amount": "Value of fine amount of car",
                                    "brand": "Brand of car",
                                    "category_id": "Category id of car",
                                    "created_at": "Timestamp of registered car",
                                    "specifications": [
                                        {
                                            "name": "Name of specification",
                                            "description": "Description of specification",
                                            "created_at": "Timestamp of registered specification"
                                        }
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Car ID not found."
                    }
                }
            }
        },
        "/rentals": {
            "post": {
                "tags": [
                    "Rentals"
                ],
                "summary": "Create a new rental",
                "description": "Route for creating a new rental.",
                "security": {
                    "bearerAuth": []
                },
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "car_id": {
                                        "type": "string"
                                    },
                                    "expected_return_date": {
                                        "type": "string"
                                    }
                                },
                                "example": {
                                    "car_id": "ID of car",
                                    "expected_return_date": "Timestamp expected vehicle return date."
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "total": {
                                            "type": "number"
                                        },
                                        "car_id": {
                                            "type": "string"
                                        },
                                        "user_id": {
                                            "type": "string"
                                        },
                                        "expected_return_date": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "id": "ID of rental",
                                        "total": 0,
                                        "car_id": "ID of car",
                                        "user_id": "ID of user",
                                        "expected_return_date": "Timestamp expected vehicle return date"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "'Car is unavailable' or 'There's a rental in progress for this user'"
                    }
                }
            }
        },
        "/rentals/devolutions/{rental_id}": {
            "post": {
                "tags": [
                    "Rentals"
                ],
                "summary": "Returning a rental car",
                "description": "Route for returning a rental car",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "in": "path",
                        "name": "rental_id",
                        "requerid": true,
                        "description": "Rental ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "string"
                                        },
                                        "total": {
                                            "type": "number"
                                        },
                                        "car_id": {
                                            "type": "string"
                                        },
                                        "user_id": {
                                            "type": "string"
                                        },
                                        "start_date": {
                                            "type": "string"
                                        },
                                        "end_date": {
                                            "type": "string"
                                        },
                                        "expected_return_date": {
                                            "type": "string"
                                        },
                                        "created_at": {
                                            "type": "string"
                                        },
                                        "updated_at": {
                                            "type": "string"
                                        }
                                    },
                                    "example": {
                                        "id": "ID of rental",
                                        "total": 0,
                                        "car_id": "ID of car",
                                        "user_id": "ID of user",
                                        "start_date": "Timestamp rental start date",
                                        "end_date": "Timestamp rental end date",
                                        "expected_return_date": "Timestamp Expected vehicle return date",
                                        "created_at": "Timestamp of registered rental",
                                        "updated_at": "Timestamp of updated rental"
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Rental dos not exist!"
                    }
                }
            }
        },
        "/rentals/users": {
            "get": {
                "tags": [
                    "Rentals"
                ],
                "summary": "List all rentals for a user",
                "description": "Lists all cars rented by a specific user",
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "total": {
                                                "type": "number"
                                            },
                                            "car_id": {
                                                "type": "string"
                                            },
                                            "user_id": {
                                                "type": "string"
                                            },
                                            "start_date": {
                                                "type": "string"
                                            },
                                            "end_date": {
                                                "type": "string"
                                            },
                                            "expected_return_date": {
                                                "type": "string"
                                            },
                                            "created_at": {
                                                "type": "string"
                                            },
                                            "updated_at": {
                                                "type": "string"
                                            },
                                            "car": {
                                                "type": "object",
                                                "properties": {
                                                    "id": {
                                                        "type": "string"
                                                    },
                                                    "avaliable": {
                                                        "type": "boolean"
                                                    },
                                                    "name": {
                                                        "type": "string"
                                                    },
                                                    "description": {
                                                        "type": "string"
                                                    },
                                                    "daily_rate": {
                                                        "type": "number"
                                                    },
                                                    "license_plate": {
                                                        "type": "string"
                                                    },
                                                    "fine_amount": {
                                                        "type": "number"
                                                    },
                                                    "brand": {
                                                        "type": "string"
                                                    },
                                                    "category_id": {
                                                        "type": "string"
                                                    },
                                                    "created_at": {
                                                        "type": "string"
                                                    }
                                                }
                                            }
                                        }
                                    },
                                    "example": {
                                        "id": "ID of rental",
                                        "total": 0,
                                        "car_id": "ID of car",
                                        "user_id": "ID of user",
                                        "start_date": "Timestamp rental start date",
                                        "end_date": "Timestamp rental end date",
                                        "expected_return_date": "Timestamp Expected vehicle return date",
                                        "created_at": "Timestamp of registered rental",
                                        "updated_at": "Timestamp of updated rental",
                                        "car": {
                                            "id": "ID of car",
                                            "avaliable": "true or false",
                                            "name": "Name of car",
                                            "description": "Description of car",
                                            "daily_rate": "Value of daily rate of car",
                                            "license_plate": "license plate of car",
                                            "fine_amount": "Value of fine amount of car",
                                            "brand": "Brand of car",
                                            "category_id": "Category id of car",
                                            "created_at": "Timestamp of registered car"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schemaCategoriesSpecifications": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            }
        },
        "Car": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "daily_rate": {
                    "type": "number"
                },
                "license_plate": {
                    "type": "string"
                },
                "fine_amount": {
                    "type": "number"
                },
                "brand": {
                    "type": "string"
                },
                "category_id": {
                    "type": "string"
                }
            }
        }
    },
    "components": {
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}